;----------------------------------------------------------------

;Include文件定义

;----------------------------------------------------------------
INCLUDELIB kernel32.lib
INCLUDELIB user32.lib
INCLUDELIB gdi32.lib
INCLUDELIB comctl32.lib
INCLUDELIB winmm.lib
INCLUDELIB masm32.lib
INCLUDELIB comdlg32.lib
INCLUDELIB shell32.lib

INCLUDE windows.inc
INCLUDE user32.inc
INCLUDE kernel32.inc
INCLUDE gdi32.inc
INCLUDE comctl32.inc
INCLUDE winmm.inc
INCLUDE masm32.inc
INCLUDE comdlg32.inc
INCLUDE shell32.inc

INCLUDE Global.inc
INCLUDE Collision.inc
INCLUDE Draw.inc
INCLUDE mouse.inc